#
# ODM_HQ_EDIT
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += ili9881c_hd_dsi_vdo_inx_boe_zal1890.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
