obj-$(CONFIG_OPPO_COMMON_SOFT)  +=  oppo_project/
obj-$(CONFIG_OPPO_DEVICE_IFNO)  +=  oppo_devinfo/
obj-$(CONFIG_OPPO_CUSTOM)  += oppo_custom/
obj-$(CONFIG_HYPNUS_HELPER)     +=  oppo_hypnus/

#ifdef VENDOR_EDIT
#Weican.Zhao@PSW.NW.EM, 2019/02/12, Add for OPPO Critical log
#obj-$(CONFIG_OPPO_CRITICALLOG)  +=  oppo_criticallog/
obj-y     +=  oppo_criticallog/
#endif /* VENDOR_EDIT */

#ifdef VENDOR_EDIT
#//wenbin.liu@PSW.Kernel.MM, 2018/05/23, Add for Healthinfo monitor
obj-y     +=  oppo_healthinfo/
#endif /* VENDOR_EDIT */
