#
# ODM_HQ_EDIT
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += hx8394f_hd_dsi_vdo_hlt_hsd_zal1890.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
