# include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-$(CONFIG_OPPO_COMMON_SOFT) += oppo_project.o
ccflags-y += -I$(srctree)/drivers/misc/mediatek/masp/asfv2//asf_inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/masp/asfv2/asf_export_inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/masp/asfv2/module