#ifdef VENDOR_EDIT
#John.Xu@PhoneSw.AudioDriver, 2016/02/22, Add for critical_log
#obj-$(CONFIG_OPPO_CRITICALLOG)	+=  oppo_criticallog.o
obj-y	+=  oppo_criticallog.o criticallog_class.o
#endif /* VENDOR_EDIT */
