#
# Copyright (C) 2018 OPPO Mobile Comm Corp. Ltd.
# ODM_HQ_EDIT
#
# File: Makefile
# Description: makefile for proc devinfo
# Author: duwenchao@ODM_HQ.BSP.system

obj-y := hq_devinfo.o
obj-y += oppoversion.o
obj-y += vitualsar.o
obj-y += sddetect.o